config/routes.rb
Wiiki::Application.routes.draw do
  resources :messages

  resources :projects

  resources :employees

  resources :siteinfos

  resources :posts do
    resources :comments, :only => [:create]
  end

  get "sessions/new"

  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "about" => "employees#index", :as => "about"
  get "home" => "siteinfos#index", :as => "home"
  get "blog" => "posts#index", :as => "blog"
  get "contact" => "messages#new", :as => "contact"

  root :to => "siteinfos#index"
  resources :users
  resources :sessions

end

app/models/siteinfo.rb
class Siteinfo < ActiveRecord::Base
	attr_accessible :banner, :blurb, :about
  has_attached_file :banner, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/siteinfos_controller.rb
class SiteinfosController < ApplicationController
    skip_before_filter :require_login, :only => :index
  # GET /siteinfos
  # GET /siteinfos.json
  def index
    @siteinfos = Siteinfo.limit(1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @siteinfos }
    end
  end

  # GET /siteinfos/1
  # GET /siteinfos/1.json
  def show
    @siteinfo = Siteinfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @siteinfo }
    end
  end

  # GET /siteinfos/new
  # GET /siteinfos/new.json
  def new
    @siteinfo = Siteinfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @siteinfo }
    end
  end

  # GET /siteinfos/1/edit
  def edit
    @siteinfo = Siteinfo.find(params[:id])
  end

  # POST /siteinfos
  # POST /siteinfos.json
  def create
    @siteinfo = Siteinfo.new(params[:siteinfo])

    respond_to do |format|
      if @siteinfo.save
        format.html { redirect_to @siteinfo, notice: 'Siteinfo was successfully created.' }
        format.json { render json: @siteinfo, status: :created, location: @siteinfo }
      else
        format.html { render action: "new" }
        format.json { render json: @siteinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /siteinfos/1
  # PUT /siteinfos/1.json
  def update
    @siteinfo = Siteinfo.find(params[:id])

    respond_to do |format|
      if @siteinfo.update_attributes(params[:siteinfo])
        format.html { redirect_to @siteinfo, notice: 'Siteinfo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @siteinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /siteinfos/1
  # DELETE /siteinfos/1.json
  def destroy
    @siteinfo = Siteinfo.find(params[:id])
    @siteinfo.destroy

    respond_to do |format|
      format.html { redirect_to siteinfos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/siteinfos_helper.rb
module SiteinfosHelper
end

app/views/siteinfos/_form.html.erb
<%= form_for(@siteinfo) do |f| %>
  <% if @siteinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@siteinfo.errors.count, "error") %> prohibited this siteinfo from being saved:</h2>

      <ul>
      <% @siteinfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row-fluid">
    <div class="span4">
      <%= f.label :welcome_to_gg %><br />
      <%= f.text_area :blurb, :required => true  %>
    </div>
    <div class="span4">
      <%= f.label :about_us %><br />
      <%= f.text_area :about, :required => true  %>
    </div>
    <div class="span4">
    <%= f.label :banner %>
    <p>Recomended resolution for banner: 1090x540</p>
    <%= f.file_field :banner %>
    </div>
</div>
   <%= f.submit "Publish info" %>
  
<% end %>

app/views/siteinfos/edit.html.erb
 <% if current_user %>
   <div class="admin-bar span12"> 
<%= link_to 'Back to home', siteinfos_path %>
   </div>
 <% end %>

<h1>Editing info</h1>

<%= render 'form' %>

app/views/siteinfos/index.html.erb
<% @siteinfos.each do |siteinfo| %>
<div class="row-fluid">
	<% if current_user %>
	<div class="admin-bar span12"> 
		<%#= link_to 'New Info', new_siteinfo_path %> 
		<%= link_to 'Edit the info', edit_siteinfo_path(siteinfo) %>
	</div>
	<% end %>
</div>

  <section class="row-fluid">
       <div class="span12 homebanner img-clean">
        <div><%= image_tag siteinfo.banner  if siteinfo.banner.file?%></div>
      </div>
  </section>
<div class="row-fluid">
	<div class="span6 ticket tick">
		<h3>Welcome to Gatling Goat</h3>
		<%=simple_format siteinfo.blurb %>
	</div>

	<div class="span6 ticket tick">
		<h3>Who are we?</h3>
		<%=simple_format siteinfo.about %>
	</div>
	<% end %>
</div>
</br>

<div class="row-fluid">
<div class="well navstripe">
<div class="span4"><b>Spread the word</b></div>
<div class="span4">

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
<a class="addthis_button_facebook"></a>
<a class="addthis_button_twitter"></a>
<a class="addthis_button_pinterest_share"></a>
<a class="addthis_button_tumblr"></a>
<a class="addthis_button_google_plusone_share"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-52737a9a0d887f92"></script>
<!-- AddThis Button END -->
</div>
<div class="span4">
<div class="fb-like" data-href="https://www.facebook.com/gatlinggoatstudios?ref=stream&amp;hc_location=stream" data-width="100%" data-colorscheme="light" data-layout="button" data-action="like" data-show-faces="false" data-send="false"></div>
</div>
</div>
</div>

app/views/siteinfos/new.html.erb
 <% if current_user %>
   <div class="admin-bar span12"> 
<%= link_to 'Back to home', siteinfos_path %>
   </div>
 <% end %>

<h1>New info</h1>

<%= render 'form' %>

app/views/siteinfos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit again', edit_siteinfo_path(@siteinfo) %> |
<%= link_to 'Show', siteinfos_path %>