config/routes.rb
Wiiki::Application.routes.draw do
  resources :messages

  resources :projects

  resources :employees

  resources :siteinfos

  resources :posts do
    resources :comments, :only => [:create]
  end

  get "sessions/new"

  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "about" => "employees#index", :as => "about"
  get "home" => "siteinfos#index", :as => "home"
  get "blog" => "posts#index", :as => "blog"
  get "contact" => "messages#new", :as => "contact"

  root :to => "siteinfos#index"
  resources :users
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :captcha, :captcha_key, :body
  apply_simple_captcha
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	  attr_accessible :avatar, :name, :title, :link, :email
  has_attached_file :avatar, :styles => { :medium => "100x100>", :thumb => "100x100>" }
end

app/models/message.rb
class Message < ActiveRecord::Base
	attr_accessible :captcha, :captcha_key, :email, :subject, :body, :name
	validates :email, email_format: { message: " doesn't look like an email address" }
	  apply_simple_captcha
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :image
  has_attached_file :image, :styles => { :medium => "100x100>", :thumb => "100x100>" }

  has_many :comments

  validates_presence_of :body, :title, :image
end

app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessible :background, :screenshot1, :screenshot2, :screenshot3, :screenshot4, :screenshot5, :screenshot6, :banner, :desc, :title, :trailer
  has_attached_file :background, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :screenshot1, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :screenshot2, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :screenshot3, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :screenshot4, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :screenshot5, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :screenshot6, :styles => { :medium => "100x100>", :thumb => "100x100>" }
  has_attached_file :banner, :styles => { :medium => "100x100>", :thumb => "100x100>" }

end

app/models/siteinfo.rb
class Siteinfo < ActiveRecord::Base
	attr_accessible :banner, :blurb, :about
  has_attached_file :banner, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_filter :require_login
        def create
                @post = Post.find(params[:post_id])
                @comment = @post.comments.create!(params[:comment])
                redirect_to @post
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login
	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to root_url, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
def show_project_background
    "background:transparent url(#{@project.background}); background-size: cover; background-repeat: no-repeat;"
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/siteinfos_helper.rb
module SiteinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Gatling Goat Studios - Walking up the stairs, kicking down the shark.</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://platform.tumblr.com/v1/share.js"></script>
  <div class="pull-right alig-right">
  <% if current_user %>
  <div id="curr"> Logged in as <%= current_user.email %>.</div>
  <%= link_to "Log out", log_out_path %>
  <% else %>
  <div id="curr"><%= link_to 'Login', log_in_path%></div>
  <% end %>
  </div>
</br>
</head>
<body>
  <div class="navstripe" >
    <div class="row-fluid">
    <div class="span2"></div>
    <div class="span8">
    <div class="row-fluid navfont img-clean">
        <div class="span4"><%=link_to image_tag('logo.png'), home_path, :id=>"logo"%></div>
        <div class="span7">
          <br/>
          <br/>
          <ul class="nav nav-pills">
            <li class="<%= 'place disabled' if current_page?(home_path) %>">
              <%= link_to 'Home', home_path%></li>

            <li class="<%= 'place disabled' if current_page?(projects_path) %>">
              <%= link_to 'Projects', projects_path%></li>

            <li class="<%= 'place disabled' if current_page?(about_path) %>">
              <%= link_to 'About us', about_path%></li>

            <li class="<%= 'place disabled' if current_page?(blog_path) %>">
              <%= link_to 'Blog', blog_path%></li>

            <% if current_user %>
            <li class="<%= 'place disabled' if current_page?(messages_path) %>">
              <%= link_to 'Messages', messages_path%></li>
            <% else %>
            <li class="<%= 'place disabled' if current_page?(contact_path) %>">
              <%= link_to 'Contact', contact_path%></li>
            <% end %>
          </ul>
        </div>
      </div>
      </div>
      <div class="span3"></div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid ">
        <div class="span2"></div>
        <div class="span8">
          <%= yield %>
          <br />
          <div class="footnote alig-right"><p>
Copyright © 2013 Carl Rockman</p></div>
        </div>
        <div class="span2"></div>
      </div>
    </div>

    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    </body>
    </html>

app/views/layouts/game.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Gatling Goat Studios - Walking up the stairs, kicking down the shark.</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://platform.tumblr.com/v1/share.js"></script>
  <div class="pull-right alig-right">
  <% if current_user %>
  <div id="curr"> Logged in as <%= current_user.email %>.</div>
  <%= link_to "Log out", log_out_path %>
  <% else %>
  <div id="curr"><%= link_to 'Login', log_in_path%></div>
  <% end %>
  </div>
</br>
</head>
<body>
  <div class="navstripe">
    <div class="row-fluid">
    <div class="span2"></div>
    <div class="span8">
    <div class="row-fluid navfont img-clean">
        <div class="span4"><%=link_to image_tag('logo.png'), home_path, :id=>"logo"%></div>
        <div class="span7">
          <br/>
          <br/>
          <ul class="nav nav-pills">
            <li class="<%= 'place disabled' if current_page?(home_path) %>">
              <%= link_to 'Home', home_path%></li>

            <li class="<%= 'place disabled' if current_page?(project_path) %>">
              <%= link_to 'Projects', projects_path%></li>

            <li class="<%= 'place disabled' if current_page?(about_path) %>">
              <%= link_to 'About us', about_path%></li>

            <li class="<%= 'place disabled' if current_page?(blog_path) %>">
              <%= link_to 'Blog', blog_path%></li>

            <% if current_user %>
            <li class="<%= 'place disabled' if current_page?(messages_path) %>">
              <%= link_to 'Messages', messages_path%></li>
            <% else %>
            <li class="<%= 'place disabled' if current_page?(contact_path) %>">
              <%= link_to 'Contact', contact_path%></li>
            <% end %>
          </ul>
        </div>
      </div>
      </div>
      <div class="span3"></div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid ">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </body>
    </html>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>